language: java
sudo: true
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_key -in all.gpg.gpg -out all.gpg -d
after_success:
  - mvn clean cobertura:cobertura coveralls:report
